moja_krotka= (10, 2, 6, 6, 9, 13, 0,1)
lista_pomocnicza = list(moja_krotka)
lista_pomocnicza.sort()
moja_krotka_posortowana = tuple(lista_pomocnicza)
print("Posortowana krotka:", moja_krotka_posortowana)